
version: 2

models:
  - name: raw_data_accounts
    description: "Raw data of accounts"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: raw_data_orders
    description: "Raw data of orders"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
